FROM react-dev:latest

# RUN npm install
# WORKDIR /BookTracker-Frontend/book-tracker-frontend
# COPY . . /BookTracker-Frontend/book-tracker-frontend/
# RUN npm install
# RUN npm run build
# EXPOSE 3001
# CMD ["npm", "start"]
# # building the app
# # RUN npm i
# # RUN npm run build
# RUN npm run build
# RUN npm start
# # # Running the app
# # CMD [ "npm", "start" ]